GF.Web/Controllers/TutorialController.cs
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591//  Ignore "Missing XML Comment" warning


using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GenericSearch.Core;
using GenericSearch.UI.Models;
using Newtonsoft.Json;

using System.Data.Entity.Repository;
using Application.Helpers;
using GF.Data.Model;
using GF.Data.Security;
using System.Web.Security;
using System.Text;
using System.Security.Cryptography;
using System.Globalization;
using System.Data.SqlClient;
using Common.Logging;
using AutoMapper;
using System.Data.Entity.Repository.Attributes;
using System.ComponentModel.DataAnnotations.Schema;
using static GF.Data.Model.ConstantesModel;

namespace GF.Controllers {

    //[Authorize(Roles = "Admin")]
    [Authorize]
    public partial class TutorialController : Controller
    {


        [AllowAnonymous]
        public ActionResult Index()	
        {
            
            return View();

        }

        
    }
}

GF.Web/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="pull-right">
        Montreal Informática
    </div>
    <div>
        <strong>SARS</strong>
    </div>
</div>

GF.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SAFI | @ViewBag.Title</title>
    <link rel="shortcut icon" href="~/favicon.ico">
    @Styles.Render("~/Content/css")
    @Styles.Render("~/font-awesome/css")



    <!-- include your less or built css files  -->
    <!--
    bootstrap-datetimepicker-build.less will pull in "../bootstrap/variables.less" and "bootstrap-datetimepicker.less";
    or
    <link rel="stylesheet" href="/Content/bootstrap-datetimepicker.css" />
    -->
    <body>
        <!-- Wrapper-->
        <div id="wrapper">
            <!-- Navigation -->
            @Html.Partial("_Navigation")
            <!-- Page wraper -->
            <div id="page-wrapper" class="gray-bg">
                <!-- Top Navbar -->
                @Html.Partial("_TopNavbar")
                <!-- Main view  -->
                @RenderBody()
                <!-- Footer -->
                @Html.Partial("_Footer")
            </div>
            <!-- End page wrapper-->
        </div>
        <!-- End wrapper-->

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/inspinia")
        @Scripts.Render("~/bundles/jqueryunobtrusive")
        @Scripts.Render("~/bundles/bootstrap")

        @Scripts.Render("~/bundles/modernizr")

        @Scripts.Render("~/bundles/datepicker")
        @Scripts.Render("~/Scripts/moment.min.js")
        @Scripts.Render("~/Scripts/bootstrap-datetimepicker.js")
        @Scripts.Render("~/Scripts/select2.js")
        
        @Scripts.Render("~/Scripts/bootbox.js")
        @Scripts.Render("~/Scripts/jquery.steps.js")
        @Scripts.Render("~/Scripts/jquery.mask.js")
        @Scripts.Render("~/Scripts/_partialScriptInicialize.js")

        <script>

            $(document).ready(function () {
                //$('#Pessoa_CPF').mask('?999.999.999-99', { reverse: true });
                //$('#Pessoa_Telefone_Fixo').mask('?(99)99999-9999', { reverse: true });
                //$('#Pessoa_Telefone_Celular').mask('?(99)99999-9999', { reverse: true });
                //$("#CEP").mask("?99.999-999", { reverse: true });
                //$('#Salario').mask('000.000.000.000.000,00', { reverse: true });

//                $('.date').mask('00/00/0000');
                $('.time').mask('00:00:00');
                $('.date_time').mask('00/00/0000 00:00:00');
                $('.cep').mask('00000-000');
                $('.phone').mask('0000-0000');
                $('.phone_with_ddd').mask('(00) 00000-0000');
                $('.phone_us').mask('(000) 000-0000');
                $('.mixed').mask('AAA 000-S0S');
                $('.cpf').mask('000.000.000-00', { reverse: true });
                $('.cnpj').mask('00.000.000/0000-00', { reverse: true });
                $('.money').mask('000000000000000,00', { reverse: true });
                $('.money2').mask("#.##0,00", { reverse: true });
                $('.ip_address').mask('0ZZ.0ZZ.0ZZ.0ZZ', {
                    translation: {
                        'Z': {
                            pattern: /[0-9]/, optional: true
                        }
                    }
                });
                $('.ip_address').mask('099.099.099.099');
                $('.percent').mask('##0,00%', { reverse: true });
                $('.clear-if-not-match').mask("00/00/0000", { clearIfNotMatch: true });
                $('.placeholder').mask("00/00/0000", { placeholder: "__/__/____" });
                $('.fallback').mask("00r00r0000", {
                    translation: {
                        'r': {
                            pattern: /[\/]/,
                            fallback: '/'
                        },
                        placeholder: "__/__/____"
                    }
                });
                $('.selectonfocus').mask("00/00/0000", { selectOnFocus: true });



                $('input[type=text]').each(function () {
                    var req = $(this).attr('data-val-required');
                    if (undefined != req) {
                        var label = $('label[for="' + $(this).attr('id') + '"]');
                        var text = label.text();
                        if (text.length > 0) {
                            label.append('<span style="color:red"> *</span>');
                        }
                    }
                });
                $('input[type=number]').each(function () {
                    var req = $(this).attr('data-val-required');
                    if (undefined != req) {
                        var label = $('label[for="' + $(this).attr('id') + '"]');
                        var text = label.text();
                        if (text.length > 0) {
                            label.append('<span style="color:red"> *</span>');
                        }
                    }
                });



            }
            )
        </script>




        @RenderSection("scripts", required: false)
        @RenderSection("AditionalJS", required: false)



    </body>
    
</html>

GF.Web/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SAFI | Login</title>
    <link rel="shortcut icon" href="~/favicon.ico">
    @Styles.Render("~/Content/css")
    @Styles.Render("~/font-awesome/css")
    @Styles.Render("~/Content/Layout.css")
    


    <script src="~/api/AbpServiceProxies/GetAll"></script>
    <script src="~/AbpScripts/GetScripts" type="text/javascript"></script>
    @RenderSection("Scripts", false)
</head>
<body>
    @RenderBody()
</body>
</html>

GF.Web/Views/Shared/_LayoutModal.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SAFI | @ViewBag.Title</title>
    <link rel="shortcut icon" href="~/favicon.ico">
    

    <body>
        
        @RenderBody()
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/inspinia")
        @Scripts.Render("~/bundles/jqueryunobtrusive")
        @Scripts.Render("~/bundles/bootstrap")

        @Scripts.Render("~/bundles/modernizr")

        @Scripts.Render("~/bundles/datepicker")
        @Scripts.Render("~/Scripts/moment.min.js")
        @Scripts.Render("~/Scripts/bootstrap-datetimepicker.js")
        @Scripts.Render("~/Scripts/select2.js")
        @Scripts.Render("~/Scripts/fullcalendar.js")
        @Scripts.Render("~/Scripts/bootbox.js")
        @Scripts.Render("~/Scripts/jquery.steps.js")
        @Scripts.Render("~/Scripts/jquery.mask.js")
        @Scripts.Render("~/Scripts/_partialScriptInicialize.js")






        @RenderSection("scripts", required: false)
        @RenderSection("AditionalJS", required: false)



    </body>
    
</html>

GF.Web/Views/Shared/_Navigation.cshtml
@using Application.Helpers.Html
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a href="@Url.Action("","Manage")">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">
                                    @User.Identity.Name
                                </strong>
                            </span>
                        </span>
                    </a>

                </div>
                <div class="logo-element">
                    <a href="@Url.Action("index","manage")">GF</a>
                </div>
            </li>


            
            <li class="@Html.IsSelected(controller: "Home")"><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> <span class="nav-label">Home</span> </a>
            
            <li>
                <a href="#"><i class="fa fa-plus-square-o"></i> <span class="fa arrow"></span><span class="nav-label">Cadastro</span></a>
                <ul class="nav nav-second-level" id="side-menu2">
                    <li class="@Html.IsSelected(controller: "Funcionario",action: "Index-Edit-Create-Delete-Details")"><a href="@Url.Action("Index", "Funcionario")"><i class="fa fa-user"></i> <span class="nav-label">Funcionários</span> </a>
                    <li class="@Html.IsSelected(controller: "Plano",action: "Index-Edit-Create-Delete-Details")"><a href="@Url.Action("Index", "Plano")"><i class="fa fa-pencil-square-o"></i> <span class="nav-label">Planos / Serviços</span> </a>
                    <li class="@Html.IsSelected(controller: "Aluno",action: "Index-Edit-Create-Delete-Details")"><a href="@Url.Action("Index", "Aluno")"><i class="fa fa-users"></i> <span class="nav-label">Alunos</span> </a>
                    <li class="@Html.IsSelected(controller: "Contrato",action: "Index-Edit-Create-Delete-Details")"><a href="@Url.Action("Index", "Contrato")"><i class="fa fa-file"></i> <span class="nav-label">Contratos</span> </a>
                    
                </ul>
                <!-- /.nav-second-level -->
            </li>

            <li>
                <a href="#"><i class="fa fa-spinner"></i> <span class="fa arrow"></span><span class="nav-label">Operações</span></a>
                <ul class="nav nav-second-level" id="side-menu4">

                    
                    <li class="@Html.IsSelected(controller: "RegistroAtividade",action: "Index-Edit-Create-Delete-Details")"><a href="@Url.Action("Index", "RegistroAtividade")"><i class="fa fa-bolt" aria-hidden="true"></i> <span class="nav-label">Registro de Atividades</span> </a>
                </ul>
                <!-- /.nav-second-level -->
            </li>

           

            <li>
                <a href="#"><i class="fa fa-area-chart"></i> <span class="fa arrow"></span><span class="nav-label">Relatórios</span></a>
                <ul class="nav nav-second-level" id="side-menu4">
                    
                    <li class="@Html.IsSelected(controller: "RelatorioFrequencia", action: "Index-Edit-Create-Delete-Details")"><a href="@Url.Action("Index", "RelatorioFrequencia")"><i class="fa fa-tasks"></i> Relatório de Frequência </a>
                    <li class="@Html.IsSelected(controller: "EntradaSaidaAlunos", action: "Index-Edit-Create-Delete-Details")"><a href="@Url.Action("Index", "EntradaSaidaAlunos")"><i class="fa fa-line-chart"></i> Entrada e Saída de Alunos </a>
                    
                </ul>
                <!-- /.nav-second-level -->
            </li>



            <!--<li class="@Html.IsSelected(controller: "Grupo", action: "Index-Edit-Create-Delete-Details")"><a href="@Url.Action("Index", "Grupo")"><i class="fa fa-users"></i> <span class="nav-label">Grupos</span> </a>-->
            <li class="@Html.IsSelected(controller: "Sair", action: "Index-Edit-Create-Delete-Details")"><a href="@Url.Action("Index", "Tutorial")"><i class="glyphicon glyphicon-expand"></i> <span class="nav-label">Tutorial</span> </a>
            <li class="@Html.IsSelected(controller: "Sair", action: "Index-Edit-Create-Delete-Details")"><a href="@Url.Action("Sair", "Funcionario")"><i class="fa fa-sign-out"></i> <span class="nav-label">Sair</span> </a>
        </ul>

    </div>  
</nav>

GF.Web/Views/Shared/_Navigation1.cshtml
@using Application.Helpers.html
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">Example user</strong>
                            </span> <span class="text-muted text-xs block">Example menu <b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="#">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>
            
            <li class="@Html.IsSelected(action: "index,create,edit,delete", controller:"Usuario")">
                <a href="@Url.Action("Index", "Usuario")"><i class="fa fa-desktop"></i> <span class="nav-label">Usuários</span></a>
            </li>
            <li class="@Html.IsSelected(action: "Usuario")">
                <a href="@Url.Action("Index", "Usuario")"><i class="fa fa-desktop"></i> <span class="nav-label">Usuários</span></a>
            </li>
            <li class="@Html.IsSelected(action: "Usuario")">
                <a href="@Url.Action("Index", "Usuario")"><i class="fa fa-desktop"></i> <span class="nav-label">Usuários</span></a>
            </li>
            <li class="@Html.IsSelected(action: "Usuario")">
                <a href="@Url.Action("Index", "Usuario")"><i class="fa fa-desktop"></i> <span class="nav-label">Usuários</span></a>
            </li>
            <li class="@Html.IsSelected(action: "Index", controller:"Home")">
                <a href="@Url.Action("Index", "Home")"><i class="fa fa-laptop"></i> <span class="nav-label">Inicio</span> </a>
            </li>
        </ul>
    </div>
</nav>

GF.Web/Views/Shared/_TopNavbar.cshtml
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <!--<form role="search" class="navbar-form-custom" method="post" action="">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                </div>
            </form>
                -->
        </div>
        @Html.Partial("_LoginPartial")
    </nav>
</div>